### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by aydv** [pdyban/driverchallenge#16]
Hi pdyban ,

Thanks a lot for sharing your code and experience in this contest. I am at the moment studying the driving behaviour area and unfortunately axa has deleted the data for this contest. Do you happen to have the full dataset that you can share?

Many thanks again and look forward to your kind feedback,
Ankit

**Comment by pdyban** [comment]
Dear Ankit,
unfortunately I do not have the data anymore.

Best,
Paul

**Comment by aydv** [comment]
No worries man, thanks for letting me know.

Cheers Ankit
